atlas:
  container_name: atlas
  image: gabethecabbage/atlas
  environment:
    - SERVERMAP=Ocean
    - SERVERPASSWORD="" 
    - ADMINPASSWORD=adminpassword
    - BACKUPONSTART=1
    - UPDATEONSTART=1
    - TZ=Europe/Paris
    - GID=1000
    - UID=1000
  volumes:
    - /my/path/to/atlas:/atlas
  ports:
   - 5750:5750/udp
   - 5750:5750
   - 57550:57550/udp
   - 57550:57550
   - 32330:32330
